name = "talk-signal"
main = "worker-talk.js"
compatibility_date = "2024-12-01"

[[durable_objects.bindings]]
name = "TALK_SESSION"
class_name = "TalkSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TalkSession"]
